global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "consul-services"
    consul_sd_configs:
      - server: "consul:8500"
        services: []
    metrics_path: "/actuator/prometheus"
    relabel_configs:
      - source_labels: ["__meta_consul_service"]
        target_label: "service"
      - source_labels:
          ["__meta_consul_service_address", "__meta_consul_service_port"]
        separator: ":"
        target_label: "__address__"
