scrape_configs:
  - job_name: "consul"
    consul_sd_configs:
      - server: "http://consul:8500"
        services: [] # vide = tous les services
    relabel_configs:
      - source_labels: ["__meta_consul_service"]
        target_label: "service"
      - source_labels:
          ["__meta_consul_service_address", "__meta_consul_service_port"]
        separator: ":"
        target_label: "__address__"
        replacement: "$1:$2"
